name: Build and Deploy React App

on:
  push:
    branches:
      - main  # Ganti dengan nama branch yang kamu gunakan

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install

      - name: Build React App
        run: |
          npm run build

      - name: Deploy via SSH to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "build/*"
          target: ${{ secrets.VPS_TARGET_DIR }}
